"""Episode audio branding — intro jingle, spoken title, outro chime.

Caches the jingle, 'presents:' speech, and outro on disk so only the
per-episode title needs TTS at runtime.  The title is generated by the
content audio workers (no separate model load).
"""

import hashlib
import os
import wave

import numpy as np


SAMPLE_RATE = 24000
_CACHE_DIR = os.path.expanduser("~/.config/a2pod/audio_cache")


def _cache_key(voice: str, speed: float, podcast_name: str) -> str:
    """Stable hash for the (voice, speed, podcast_name) combo."""
    raw = f"{voice}:{speed}:{podcast_name}"
    return hashlib.md5(raw.encode()).hexdigest()[:12]


def generate_jingle(output_path: str, sample_rate: int = SAMPLE_RATE) -> str:
    """Generate a pleasant bell/chime chord programmatically.

    C major triad (C5+E5+G5+C6) with exponential decay and a softer
    second strike at t=0.6s for a "ding-ding" feel. ~2.5s duration.
    """
    import soundfile as sf

    duration = 2.5
    t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)

    # C major chord: C5(523), E5(659), G5(784), C6(1047)
    freqs = [523.25, 659.25, 783.99, 1046.50]
    chord = sum(np.sin(2 * np.pi * f * t) for f in freqs)

    # Exponential decay envelope
    envelope = np.exp(-t * 2.5)
    strike1 = chord * envelope

    # Second softer strike at t=0.6s
    offset_samples = int(0.6 * sample_rate)
    strike2 = np.zeros_like(t)
    t2 = t[:-offset_samples] if offset_samples > 0 else t
    chord2 = sum(np.sin(2 * np.pi * f * t2) for f in freqs)
    envelope2 = np.exp(-t2 * 3.0) * 0.5
    strike2[offset_samples:] = (chord2 * envelope2)[:len(strike2) - offset_samples]

    audio = strike1 + strike2

    # Normalize to 0.4 peak amplitude
    peak = np.max(np.abs(audio))
    if peak > 0:
        audio = audio * (0.4 / peak)

    sf.write(output_path, audio.astype(np.float32), sample_rate)
    return output_path


def _generate_presents_speech(
    voice: str, speed: float, output_path: str, podcast_name: str,
) -> str:
    """Speak '<podcast_name> presents:' in a subprocess to avoid Metal GPU conflicts."""
    import multiprocessing as mp
    import subprocess
    import sys

    # Run TTS in a completely separate process so the parent never loads MLX.
    # This prevents Metal GPU context conflicts with worker processes.
    script = f"""\
import os, logging, warnings
import numpy as np
logging.disable(logging.WARNING)
os.environ["HF_HUB_DISABLE_PROGRESS_BARS"] = "1"
import soundfile as sf
from mlx_audio.tts.utils import load_model
model = load_model("mlx-community/Kokoro-82M-bf16")
audio_segments = []
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    for result in model.generate({repr(f"{podcast_name} presents:")}, voice={repr(voice)}, speed={speed}, lang_code="a"):
        audio_segments.append(np.array(result.audio))
if not audio_segments:
    audio = np.zeros(int({SAMPLE_RATE} * 1.0), dtype=np.float32)
else:
    audio = np.concatenate(audio_segments)
sf.write({repr(output_path)}, audio, {SAMPLE_RATE})
"""
    result = subprocess.run(
        [sys.executable, "-c", script],
        capture_output=True, timeout=120,
    )
    if result.returncode != 0:
        # Fallback: generate silence
        generate_silence(1.0, output_path)
    return output_path


def generate_outro(output_path: str, sample_rate: int = SAMPLE_RATE) -> str:
    """Generate an ending chime with silence padding.

    2s silence → C major chord with gentle decay → 3s silence.
    Softer and slower decay than the intro jingle.  ~7.5s total.
    """
    import soundfile as sf

    chime_duration = 2.5
    pre_silence = 2.0
    post_silence = 3.0

    t = np.linspace(0, chime_duration, int(sample_rate * chime_duration), endpoint=False)

    freqs = [523.25, 659.25, 783.99, 1046.50]
    chord = sum(np.sin(2 * np.pi * f * t) for f in freqs)

    # Slower decay + softer amplitude than intro for a gentle wind-down
    envelope = np.exp(-t * 2.0)
    strike1 = chord * envelope

    offset_samples = int(0.6 * sample_rate)
    strike2 = np.zeros_like(t)
    t2 = t[:-offset_samples] if offset_samples > 0 else t
    chord2 = sum(np.sin(2 * np.pi * f * t2) for f in freqs)
    envelope2 = np.exp(-t2 * 2.5) * 0.4
    strike2[offset_samples:] = (chord2 * envelope2)[:len(strike2) - offset_samples]

    chime = strike1 + strike2

    peak = np.max(np.abs(chime))
    if peak > 0:
        chime = chime * (0.35 / peak)

    # Assemble: pre-silence + chime + post-silence
    pre = np.zeros(int(sample_rate * pre_silence), dtype=np.float32)
    post = np.zeros(int(sample_rate * post_silence), dtype=np.float32)
    audio = np.concatenate([pre, chime.astype(np.float32), post])

    sf.write(output_path, audio, sample_rate)
    return output_path


def generate_silence(duration: float, output_path: str, sample_rate: int = SAMPLE_RATE) -> str:
    """Generate a WAV file of silence."""
    import soundfile as sf

    samples = np.zeros(int(sample_rate * duration), dtype=np.float32)
    sf.write(output_path, samples, sample_rate)
    return output_path


def get_cached_intro_parts(
    voice: str, speed: float, tmpdir: str, podcast_name: str,
) -> tuple[str, str, str]:
    """Return (jingle_path, presents_path, silence_path), generating and caching as needed.

    The jingle, 'presents:' speech, and silence are cached on disk so they're
    only generated once per voice/speed/podcast_name combination.
    """
    os.makedirs(_CACHE_DIR, exist_ok=True)
    key = _cache_key(voice, speed, podcast_name)

    jingle_path = os.path.join(_CACHE_DIR, "jingle.wav")
    presents_path = os.path.join(_CACHE_DIR, f"presents_{key}.wav")
    silence_path = os.path.join(_CACHE_DIR, "silence.wav")

    if not os.path.exists(jingle_path):
        generate_jingle(jingle_path)

    if not os.path.exists(presents_path):
        _generate_presents_speech(voice, speed, presents_path, podcast_name)

    if not os.path.exists(silence_path):
        generate_silence(0.8, silence_path)

    return jingle_path, presents_path, silence_path


def get_cached_outro() -> str:
    """Return outro_path, generating and caching if needed."""
    os.makedirs(_CACHE_DIR, exist_ok=True)
    outro_path = os.path.join(_CACHE_DIR, "outro.wav")
    if not os.path.exists(outro_path):
        generate_outro(outro_path)
    return outro_path


def assemble_intro(jingle_path: str, presents_path: str, title_wav: str, silence_path: str) -> list[str]:
    """Assemble intro WAV list from cached parts + the title WAV.

    Returns list of WAV file paths in playback order:
    jingle → 'presents:' → title → silence
    """
    return [jingle_path, presents_path, title_wav, silence_path]


def get_intro_duration(wav_files: list[str]) -> float:
    """Sum the duration of intro WAV files."""
    total = 0.0
    for path in wav_files:
        with wave.open(path, "rb") as wf:
            total += wf.getnframes() / wf.getframerate()
    return total


# ── Legacy API (kept for sequential/single-worker fallback) ──────────────────

def generate_intro(
    title: str,
    voice: str,
    speed: float,
    tmpdir: str,
    podcast_name: str,
) -> list[str]:
    """Generate full intro: jingle + spoken title + silence buffer.

    Returns list of WAV file paths in playback order.
    """
    jingle_path, presents_path, silence_path = get_cached_intro_parts(
        voice, speed, tmpdir, podcast_name,
    )

    # Still need TTS for the title in the sequential path
    title_path = os.path.join(tmpdir, "intro_title.wav")
    _generate_title_speech(title, voice, speed, title_path)

    return [jingle_path, presents_path, title_path, silence_path]


def _generate_title_speech(title: str, voice: str, speed: float, output_path: str) -> str:
    """Speak just the title in a subprocess to avoid Metal GPU conflicts."""
    import subprocess
    import sys

    script = f"""\
import os, logging, warnings
import numpy as np
logging.disable(logging.WARNING)
os.environ["HF_HUB_DISABLE_PROGRESS_BARS"] = "1"
import soundfile as sf
from mlx_audio.tts.utils import load_model
model = load_model("mlx-community/Kokoro-82M-bf16")
audio_segments = []
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    for result in model.generate({repr(title)}, voice={repr(voice)}, speed={speed}, lang_code="a"):
        audio_segments.append(np.array(result.audio))
if not audio_segments:
    audio = np.zeros(int({SAMPLE_RATE} * 1.0), dtype=np.float32)
else:
    audio = np.concatenate(audio_segments)
sf.write({repr(output_path)}, audio, {SAMPLE_RATE})
"""
    result = subprocess.run(
        [sys.executable, "-c", script],
        capture_output=True, timeout=120,
    )
    if result.returncode != 0:
        generate_silence(1.0, output_path)
    return output_path
